#+title: lsl-mode

* About
This is a major mode for GNU Emacs for coding in Linden Scripting Language used in Second Life.

The project is in early phase of development so there aren't many features available yet.

* Contributing
Code contributions are welcome, but before you start working or send a PR, let me know what you plan on doing. You can do so by opening an issue.

If you find any problems or bugs, open an issue with a description of it.

* Disclaimer
I'm not familiar with elisp enough to say I know what I'm doing. Engage at your own risk.

* License
Copyright (C) 2022 Purrie

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
